name: build-release-latest
on:
  push:
    tags-ignore: 'v*'
    branches: '*'

jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # build container image for package creation
      - run: /usr/bin/docker build -t ${{ github.job }} -f build/Dockerfile .
      # actually build .mkp file
      - run: /usr/bin/docker run --volume $PWD:/source ${{ github.job }}
      # upload results
      - uses: actions/upload-artifact@v4
        with:
          path: ./*.mkp
          retention-days: 1

  github-release:
    runs-on: ubuntu-latest
    needs: build-package
    steps:
      - uses: actions/download-artifact@v4
      - run: cd artifact && md5sum *.mkp > md5sums.txt
      - run: cd artifact && sha256sum *.mkp > sha256sums.txt
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          files: |
            artifact/*